---
title: "Prepare: Week 03"
output: 
  html_document:
    css: "prepare.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## For Wednesday, Jan 19

**Note:** All required prepare activities are due **<u>by the beginning of class</u>** on the specified date.

### Required 

`r emo::ji("movie_camera")` Watch [Visualizing numerical data](https://youtu.be/waBabVTI8ec) 

- [Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d03-viz-num/u2-d03-viz-num.html#1)

`r emo::ji("movie_camera")` Watch [Visualizing categorical data](https://youtu.be/21h3rEO8k2E) 

- [Slides](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d04-viz-cat/u2-d04-viz-cat.html#1)

### Optional 

`r emo::ji("book")` Read [R4DS:: Chapter 3 - Data Visualization](https://r4ds.had.co.nz/data-visualisation.html)

`r emo::ji("book")` Read [Introduction to Modern Data Science (IMS):: Chapter 4 - Exploring Numerical Data](https://openintro-ims.netlify.app/explore-numerical.html)

`r emo::ji("book")` Read [IMS:: Chapter 5 - Exploring Categorical Data](https://openintro-ims.netlify.app/explore-categorical.html)
<br> 

`r emo::ji("memo")` Take Quiz 1 under Tests & Quizzes in Sakai.

- Going forward, prepare quizzes will be required. This quiz is optional to give you an opportunity to practice using Sakai quizzes. 


## For Friday, Jan 21

### Required 

**You can ignore the "Your Turn" sections.**

`r emo::ji("movie_camera")` Watch [Tidy Data](https://youtu.be/Ux85eR3h9hw)

- [Click here](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d05-tidy-data/u2-d05-tidy-data.html#1) for slides

`r emo::ji("movie_camera")` Watch [Grammar of data wrangling](https://youtu.be/ZCaYBES_VEk)

- [Click here](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d06-grammar-wrangle/u2-d06-grammar-wrangle.html#1) for slides

`r emo::ji("movie_camera")` Watch [Working with a single data frame](https://youtu.be/0229Uq2hkJo)

- [Click here](https://rstudio-education.github.io/datascience-box/course-materials/slides/u2-d07-single-df/u2-d07-single-df.html#1) for slides

<br> 

