# Navigation Bar Links
#   The weight parameter defines the order that the links will appear in.

[[main]]
   # pre = "<i class=\"fa fa-info-circle\"></i>"
    name = "Syllabus"
    url = "/syllabus/syllabus.pdf"
    weight = 10

[[main]]
    name = "Schedule"
 #    pre = "<i class=\"fa fa-calendar\" aria-hidden=\"true\"></i>"
    url = "/schedule/"
    weight = 20

[[main]]
   # pre = "<i class=\"fa fa-info-circle\"></i>"
    name = "Project"
    url = "/project/project.html"
    weight = 30


[[main]]
    # pre = "<i class=\"fa fa-graduation-cap\" aria-hidden=\"true\"></i>"
    url = "https://sakai.duke.edu"
    name = " Sakai"
    weight = 40

[[main]]
    # pre = "<i class=\"fa fa-check-square\" aria-hidden=\"true\"></i>"
    url = "https://www.gradescope.com"
    name = "Gradescope"
    weight = 50


#[[main]]
   # pre = "<i class=\"fa fa-question-circle\" aria-hidden=\"true\"></i>"
  #  name = "Help"
   # url = "/help/"
    #weight = 60
[[main]]
       # pre = "<i class=\"fa fa-info-circle\"></i>"
        name = "FAQ"
        url = "/faq/faq.html"
        weight = 60

[[main]]
    url = "https://vm-manage.oit.duke.edu/containers"
   # pre = "<i class=\"fa fa-code\" aria-hidden\"true\"></i>"
    name = "<i class=\"fab fa-r-project\"></i>"
    weight = 70

[[main]]
    url = "https://github.com/sta199-summer22"
    # pre = "<i class='fab fa-github fa-lg'></i>"
    name  = "<i class='fab fa-github fa-lg'></i>"
    weight = 80

[[main]]
    url = "https://sta199-summer22.slack.com"
    name = "<i class='fab fa-slack fa-lg'></i>"
    #name  = "<i class=\"ai ai-piazza ai-lg\"></i>"
    weight = 90
