# STA 199: Exam 02- Due Tuesday April 5th at 11:59 PM

# Instructions

The exam questions are in the README portion of the repository below.

### Deadline

This exam is due Tuesday April 5th by 11:59 PM.

You must submit a PDF document to Gradescope that corresponds to an `.Rmd` file on your GitHub repository in order to receive credit for this exam.

**With the exception of major emergencies, late submissions will not be accepted. In the case of a major emergency, you should have your Dean send the instructor an excuse. Start and submit the exam early in
order to** **avoid any last-minute technical issues.**

**You may resubmit the exam before the deadline.**

Commit and push often and at appropriate times. Commit history comprises a portion of the Workflow and Formatting grade.

### Rules

-   This is an individual assignment.
-   Everything in your repository is for your eyes only.
-   You may not collaborate or communicate anything about this exam to
    **anyone** except the instructor. For example, you may not
    communicate with other students, the TAs, or post/solicit help on
    the internet, email or via any other method of communication.
-   You may use `R`, as well as any notes, books, or existing internet
    resources to answer exam questions. If you use a resource outside of those
    we used for class, you must cite it.
-   You must also cite any code you use as inspiration. A failure to cite is
    plagiarism. Cite any sources by providing a link to the original
    source in your exam write-up.
-   No TA office hours will be held while the exam is live.
-   Do not email the TAs with questions.
-   If you have questions email the instructor. Questions should only be
    about understanding the data or the exam’s instructions. You may not
    ask questions on any topics from past assignments or material
    related to the exam.
-   The instructor will provide code debugging if needed, but this will
    result in a **grade penalty** if needed.

### Academic Integrity

By taking this exam, you pledge to uphold the Duke Community Standard:

-   I will not lie, cheat, or steal in my academic endeavors;
-   I will conduct myself honorably in all my endeavors; and
-   I will act if the Standard is compromised.

### Submission

Please only upload your PDF document to Gradescope. Before you submit
the uploaded document, mark where each answer is to the exercises. If
any answer spans multiple pages, then mark all pages. Make sure to
associate the “Workflow and formatting” section with the first page. Failure to do so may result in points** **being taken off.**

Make sure that your uploaded PDF document matches your `.Rmd` and the
PDF in your repository exactly. Points will be deducted for
non-reproducibility.
