---
title: "STA 199: Final Project"
output: 
  html_document: 
    css: "sta199-project.css"
    highlight: pygments
    toc: true
    # toc_depth: 2
    toc_float: true
---

# Timeline 

Project proposal due **Friday, June 3 at 11:59pm**

Draft report due **Monday, June 13 at 11:59pm**

Peer review due **Wednesday, June 15 at 11:59pm**

Final report and team repository due **Wednesday, June 22 at 9:29am**

Presentation on **Thursday, June 23 at 9:30am**

Peer evaluation due **Thursday, June 23 at 12pm**

# Introduction

The goal of this project is to demonstrate proficiency in data science 
techniques by conducting a novel analysis of a dataset of your own choosing
or creation. The dataset may already exist, or you may collect your own data 
using a survey. You will also practice effective oral and written communication 
of your results. 

# Brief Project Logistics

The final project will be done in groups of 3-4 members. Click [here](https://docs.google.com/spreadsheets/d/1W7IP9bBbZIAPSl0hw6FaekSFGu337vYfjaCBVOOobnM/edit?usp=sharing) to find your team number and members. 

The five deliverables for the final project are

- A project proposal describing three datasets of interest
- A written, reproducible report using R Markdown detailing your analysis
- A GitHub repository corresponding to your report
- Slides + presentation
- A formal peer review of another team's project

**Late projects will not be accepted.** 
As per the syllabus, you and your team must complete all components of the final 
project to pass the course.

The grade breakdown is as follows:

Total                                                   | 100 pts
--------------------------------------------------------|--------
**Project proposal**                                    | 5 pts
**Written report**                                      | 50 pts
**Repository**                                          | 5 pts
**Peer review**                                         | 10 pts
**Slides**                                              | 10 pts
**Presentation**                                        | 20 pts

# Data Sources

To perform a successful analysis it is imperative that you choose a manageable
dataset that can be analyzed using the tools we have learned in STA 199. This 
means that the data should be readily accessible, not contain too many missing values, 
and be large enough so that multiple relationships can be explored.
Your dataset must have at **least 500 observations and at least ten variables 
(or has been approved by your instructor)**. The dataset should include a rich 
mix of categorical, discrete numeric, and continuous numeric data. If you have 
any doubts or are having trouble please reach out to me.

All analyses must be done in RStudio and your final written report and analysis 
must be reproducible. This means that you must create an R Markdown document 
attached to a GitHub repository that will create your written report exactly 
upon knitting.

If you are using a dataset that comes in a format that we haven’t encountered 
in class (for instance, a `.DAT` file), make sure that you are able to load it 
into RStudio as this can be tricky depending on the source. If you are 
having trouble, google first, then ask for help.

Datasets that **cannot** be used:

- Datasets used as examples/homework in this class

- Data that have been analyzed in another class

- Kaggle

The resources below may be helpful for finding an interesting dataset but feel
free to explore on your own.

- [R Data Sources for Regression Analysis](https://rfun.library.duke.edu/blog/data-sources-for-regression-analysis/)
- [FiveThirtyEight data](https://data.fivethirtyeight.com/)
- [TidyTuesday](https://github.com/rfordatascience/tidytuesday)
- [World Health Organization](https://www.who.int/gho/database/en/)
- [The National Bureau of Economic Research](https://data.nber.org/data/)
- [International Monetary Fund](https://data.imf.org/?sk=388DFA60-1D26-4ADE-B505-A05A558D9A42&sId=1479329328660)
- [General Social Survey](http://gss.norc.org/)
- [United Nations Data](http://data.un.org/)
- [United Nations Statistics Division](https://unstats.un.org/home/)
- [U.K. Data](https://data.gov.uk/)
- [U.S. Data](https://www.data.gov/)
- [U.S. Census Data](https://www.census.gov/data.html)
- [European Statistics](https://ec.europa.eu/eurostat/)
- [Statistics Canada](https://www.statcan.gc.ca/eng/start)
- [Pew Research](https://www.pewresearch.org/download-datasets/)
- [UNICEF](https://data.unicef.org/)
- [CDC](https://www.cdc.gov/datastatistics/index.html)
- [World Bank](https://datacatalog.worldbank.org/)
- [Election Studies](https://electionstudies.org//)

# Project Components

## 1. Project proposal (5 pts)

The proposal serves two purposes:

- to get you started early with reading and thinking about a dataset and the
questions you want to answer
- to ensure that the data you wish to analyze, methods you plan to use, and the 
scope of your analyses are feasible and maximize your chance of success

Choose **three** substantially different datasets you are interested in analyzing. 
For each, identify the components below.

### Introduction / data

- Identify the source of the data
- When and how they were originally collected (by the curator, not necessarily how 
you found the data) 
- A brief description of the observations and variables you intend to explore 

### Research questions

- Describe the research topic along with a concise statement of the research 
question and hypotheses
- A brief plan on how you would answer your research question(s) 

### Dataset

- Use the `glimpse()` function to glimpse your data and include the output at the 
end of your proposal
- Place the file containing your data in the "data" folder of your project repo

Click [here](https://sta199-summer22.netlify.app/slides/13-projectproposal_BJ.html) for examples.

### Submission

Order your proposals from first choice to third choice.

Submit the PDF of your proposal to Gradescope by **Friday, June 3 at 11:59pm**. 
I will provide feedback on your proposal and help you decide which dataset you 
should use for your final project. Project proposals should have no more than 
one page of **text.** (With the `glimpse()` it is likely to go beyond a page total.)

The project proposal will be graded as follows:

Total                                                   | 5 pts
--------------------------------------------------------|-------
**Introduction / data**                                 | 2 pts
**Data glimpse**                                        | 1 pts
**Research questions**                                  | 2 pts

## 2. Written report (50 pts)

Your final report must be written using R Markdown. Before you finalize your report, 
make sure the printing of code chunks is turned off with the option `echo = FALSE`.

Your final report must match your GitHub repository **exactly**. The mandatory 
components of the report are as follows, but feel free to expand with additional 
sections as necessary. Your final written report should not exceed ten pages 
inclusive of all tables and figures.

The written report is worth 50 points, broken down as follows:

Total                                                   | 50 pts
--------------------------------------------------------|-------
**Introduction / data**                                 | 5 pts
**Methodology**                                         | 12 pts
**Results**                                             | 20 pts
**Discussion**                                          | 10 pts
**Formatting**                                          | 3 pts

### Introduction / data

The introduction provides motivation and context for your research. Describe
your topic (citing sources) and provide a concise, clear statement of your 
research question and hypotheses.

Then identify the source of the data, when and how they were collected, relevant 
context and a general description of relevant variables.

### Methodology 

The methodology section should include justification of the choice of 
statistical method(s) used to answer your research question. You can also include 
summary statistics or figures used in exploratory data analysis to 
investigate your research question.

### Results 

Place figure(s) here to illustrate the main results from your analysis. One 
beautiful figure is worth more than several poorly formatted figures. You should 
**not** use the default gray background `ggplot` theme.

Showcase how you arrived at answers to your research question using the
techniques we have learned in class (and beyond, if you’re feeling adventurous).

Provide only the main results from your analysis. The goal is not to do an 
exhaustive data analysis (calculate every possible statistic and perform every 
possible procedure for all variables). Rather, you should demonstrate that you 
are proficient at asking meaningful questions and answering them using data, 
that you are skilled in interpreting and presenting results, and that you can 
accomplish these tasks using R. More is not better.

### Discussion

This section is a conclusion and discussion. This will require a summary of
what you have learned about your research question along with statistical
arguments supporting your conclusions. You should critique your own methods 
and provide suggestions for improving your analysis and future work. Issues 
pertaining to the reliability and validity of your data and the appropriateness 
of the statistical analyses should also be discussed. Also include a brief 
paragraph on what you would do differently if you were able to start over with 
the project or what you would do next if you were going to continue work on the 
project.

### Formatting

Your project should be professionally formatted. For example, this means labeling 
graphs and figures, turning off code chunks, and using tidyverse style.

## 3. Repository (5 pts)

In addition to your Gradescope submissions, we will be checking your GitHub
repository. The repos should be formatted in the same manner as labs with 
a data folder. This repository should have equal contribution by all team members 
with regular meaningful commits / pushes and should include

- R Markdown file (formatted to clearly present all of your code and results)
that will output the final report in one document.
- Meaningful README file on the GitHub repository that contains a **codebook**
for relevant variables
- Dataset(s) (in csv or RData format, in a "data" folder)

Style and format does count for this assignment, so please take the time to 
make sure everything looks good and your data and code are properly formatted.

## 4. Peer review (10 pts)

Critically reviewing others’ work is a crucial part of the scientific process, 
and STA 199 is no exception. You will be assigned a team to review. As part of 
the review process, you must provide your partner team a copy of your current 
report by **Monday, June 13 at 11:59pm**. After giving the report to your partner 
team, they will have until **Wednesday, June 15 at 11:59pm** to provide a detailed 
critique about the written report and data analysis. This feedback is intended 
to help you create a high quality final project, as well as give you experience 
reading and constructively critiquing the work of others.

During the peer review process, you will be provided read-only access to your 
partner team’s GitHub repo. Provide your feedback in the form of GitHub issues 
to your partner team’s GitHub repo. Click [here](https://docs.google.com/spreadsheets/d/1W7IP9bBbZIAPSl0hw6FaekSFGu337vYfjaCBVOOobnM/edit?usp=sharing) to find your partner team.

Peer review will be graded on the extent to which it comprehensively and 
constructively addresses the components of the partner team’s report: the research 
context and motivation, exploratory data analysis, and any inference, modeling, 
or conclusions. As you work on the draft, the focus should be on the analysis 
and less on crafting the final report. Your draft must include a reasonable 
attempt at each analysis component - exploratory data analysis, inference or modeling, 
and drawing initial conclusions.

<!-- Lab on **Tuesday, June 14** will be devoted to allowing your group to  -->
<!-- write your peer review. -->

Click [here](https://sta199-summer22.netlify.app/project/peer-review_BJ.html) 
for detailed guidelines on how to create GitHub issues and relevant questions to 
answer in the peer review process.

## 5. Slides (10 pts)

For your presentation, you and your team must also create presentation slides 
that summarize and showcase your project. Introduce your research question and 
dataset, showcase visualizations, and provide some conclusions. These slides 
should serve as a brief visual accompaniment to your write-up and will be graded 
for content and quality.

The slide deck should have no more than 8 content slides + 1 title slide. Here 
is a suggested outline as you think through the slides; you do not have to use 
this exact format for the slide deck.

- Title Slide

- Slide 1: Introduce the topic and motivation

- Slide 2: Introduce the data

- Slide 3 - 5: Highlights from exploratory data analysis

- Slide 5 - 7: Inference / modeling

- Slide 8: Conclusions + future work

# Tips

- Ask questions if any of the expectations are unclear.

- Code: In your write-up your code should be hidden (`echo = FALSE`) so that 
your document is neat and easy to read. However your document should include 
all your code such that if I re-knit your Rmd file I should be able to obtain 
the results you presented. **Exception:** If you want to highlight something 
specific about a piece of code, you're welcome to show that portion. 

- Merge conflicts will happen, issues will arise, and that’s fine! 
Commit and push often, and ask questions when stuck.

- The project is very open ended. For instance, in creating compelling 
visualization of your data in `R`, there is no limit on what tools or 
packages you may use. You do not need to visualize all of the data at once. A 
single high quality visualization will receive a much higher grade than 
a large number of poor quality visualizations.

- Make sure each team member is contributing, both in terms of quality and 
quantity of contribution (we will be reviewing commits from different team 
members).

- All team members are expected to contribute equally to the completion 
of this assignment and peer evaluation will be given at its completion - 
anyone judged to not have sufficient contributed to the final product will have 
their grade penalized. 

- While different teams members may have different backgrounds and abilities, 
it is the responsibility of every team member to understand how and why all code 
and approaches in the assignment works.

- Pay attention to details in your write-up. Neatness, coherency, and 
clarity will count.

- Write all R code according to the style guidelines discussed in class. 

- Check [here](https://sta199-summer22.netlify.app/project/project-tips_BJ.html) 
for more tips on formatting and communicating results. 

# Grading

Grading of the project will take into account the following:

- Content: What is the quality of research and/or policy question and relevancy 
of data to those questions?
- Correctness: Are statistical procedures carried out and explained correctly?
- Writing + Presentation: What is the quality of the statistical presentation, 
writing, and explanations?
- Creativity and Critical Thought: Is the project carefully thought out? Are the 
limitations carefully considered? Does it appear that time and effort went into 
the planning and implementation of the project?

A general breakdown of scoring is as follows:

- **90%-100%**: Outstanding effort. Student understands how to apply all statistical 
concepts, can put the results into a cogent argument, can identify weaknesses 
in the argument, and can clearly communicate the results to others.
- **80%-89%**: Good effort. Student understands most of the concepts, puts 
together an adequate argument, identifies some weaknesses of their argument, 
and communicates most results clearly to others.
- **70%-79%**: Passing effort. Student has misunderstanding of concepts in several 
areas, has some trouble putting results together in a cogent argument, and 
communication of results is sometimes unclear.
- **60%-69%**: Struggling effort. Student is making some effort, but has 
misunderstanding of many concepts and is unable to put together a cogent argument. 
Communication of results is unclear.
- **Below 60%**: Student is not making a sufficient effort.

# Peer Evaluation

You will be asked to fill out a survey where you rate the contribution and 
teamwork of each team member by assigning a contribution percentage for each 
team member with justification. This will contribute to your final project 
grade. Final survey evaluations will be due **Thursday, June 23 at 12pm**.

# Late Work Policy

**There is no late work accepted on this project!** Be sure to turn in your work 
early to avoid any technological mishaps.
