---
title: 'Homework #02: Data Wrangling and Joins'
subtitle: 'due Thu September 23 at 11:59 PM '
output:
  tufte::tufte_html:
    tufte_variant: envisioned
    highlight: pygments
  html_document:
    df_print: paged
link-citations: yes
editor_options:
  chunk_output_type: console
---

## Goals

- Develop proficiency with data-wrangling functions
- Answer real research questions using related datasets

For this assignment you must have at least three meaningful commits and all of your code chunks must have informative names. 

For your first commit, update your author name in the YAML header of the
template R Markdown file.

All plots should follow the best visualization practices discussed in lecture, including an informative title, labeled axes, and careful consideration of aesthetic choices.

All code should follow the tidyverse style guidelines, including not exceeding the 80 character limit.

**For every `join` function you should explicitly specify the `by` argument**

# Setup
  
- Go to the [organization GitHub page](https://github.com/sta199-f21) and copy the SSH link to repository `hw02-username`, open a new project in RStudio and clone the project.

# The Class of 2018

We will work with the `tidyverse` package as usual. You may also want to use `viridis.`

```{r load-package, eval=FALSE}
library(tidyverse)
library(viridis)
```

In 2018, Democrats won the majority in Congress for the first time since the Tea Party wave in 2010. Yet within the Democratic Party, a wide variety of ideologies and perspectives exist. This dataset works with three related datasets to answer questions about Democratic members of Congress who served in the 116th Congress (2017-2019).

One ideology measure we will work with are *DW-Nominate* scores. These are created using advanced statistical methods. For the purpose of this assignment, we will be focusing on 1st Dimension DW-Nominate scores. These scores generally vary from -1 (most liberal) to 1 (most conservative). Since we are working with Democrats, all scores will be negative. If you are interested in learning more about this measure, [this article](https://www-cambridge-org.proxy.lib.duke.edu/core/journals/studies-in-american-political-development/article/nominate-and-american-political-development-a-primer/DC642ACEB095605E82EEF7EEC4AA9E01) provides a primer about it. (Reading it is not required for this assignment.)

A brief description of the datasets and how they are related to each other is provided below.

The `ideologies` dataset contains information on Democratic representatives' ideologies. Observations are uniquely identified by `bioname` and `icpsr`.

The variables in this dataset are:

- `bioname`: The name of the reprentative.
- `icpsr`: the [ICPSR](https://www.icpsr.umich.edu/web/pages/) code given to the representative.
- `state_icpsr`: The ICPSR number given to the representative's state.
- `district_code`: A code for the representative's district.
- `nominate_dim`: The representatives' first dimension DW-Nominate Score.

The `district_info` dataset contains information about the representatives' district. Observations are uniquely identified by `bioname` and `bioguide_id`.

The variables in this dataset are:

- `bioname`: The name of the reprentative.
- `bioguide_id`: the id number in the [Congressional Biogrphical Directory](https://www.congress.gov/help/field-values/member-bioguide-ids).
- `state_abbrev`: The state abbreviation for the state that the member represents.
- `trump16`: The percentage of the vote that Donald Trump received in the representatives district in 2016 (in theory, from 0 to 100).
` born`: The year the representative was born.

Members of Congress typically join a series of caucuses with representatives who have similar interests, districts, or ideologies. Within the Democratic Party, two prominent caucuses are the [Blue Dog Coalition](https://bluedogcaucus-costa.house.gov/), a group of more moderate Democrats, and the [Congressional Progressive Caucus](https://progressives.house.gov/caucus-members), which is made up of more progressive Democrats.

The `caucus` dataset contains three variables:

- `state_icpsr`: The ICPSR number given to the representative's state.
- `district_code`: A code for the representative's district.
- `caucus`: The caucus the representative is a member of. There are three options for this variable: Blue Dog, Progressive, or Neither. 

## Looking at Democrats in the 116th Congress

1. Let’s start by creating an analysis data set that includes information from all three data sets.

- First, join the `district_info` to the `ideologies` data frame. The goal is to keep all of the rows and columns in the `ideologies` data frame. Call this new data set `full_data`.

- Next, use a join to add columns from the `caucus` data frame to `full_data`. Hint: when matches may be ambiguous, you can join by more than one variable. e.g.
`blank_join(caucus, by = c("variable1, "variable2))`.

- Lastly, we need to add information to the data about the region a state is located in. We will use the region in later exercises. To do so, we will use information from two data sets that are already loaded as part of R - state.region and state.abb. Use the code below to create a tibble called `states` that includes the state abbreviation and the region. Then, use an appropriate join to add the region from `states` to `full_data`.

```states <- as_tibble(cbind(state.abb, state.region))```
                 
**The final full_data data frame should have 238 observations and 11 variables.**

We will use `full_data` for the remainder of the assignment.

2. We can see which states have the most progressive and most moderate Democratic delegations. Find the mean ideology by state and display the most progressive two states and most moderate two states. The ideology is measured by `nominate_dim1`. Show all code and output.

- Which two states have the most progressive Democratic delegations? Which have the most moderate?

- Are there any concerns you have with using these values to represent the mean ideology for a state’s delegation? Briefly explain.

3. Which 9 states do not have a Democratic representative? Use the states data frame and an appropriate join to help answer this question. Show all code and output, and report the names of the states in your narrative.

4. Is there a relationship between the percentage of the vote Donald Trump received in a district in 2016 and the DW-Nominate score for the district’s representative? to answer this question:

- Find the correlation between these two variables.

- Make a visualization showing the relationship between trump_16 and nominate_dim1. Include an informative title and axis labels.

- Interpret the plot.

5. Now let’s look at data for caucus. Calculate the mean and standard deviation of ideology and the number of representatives for each caucus.

- Which caucus is the most progressive?

- Which group has the most variability in ideology?

- Which is the largest group?

6. Let’s examine how caucus membership differs by region. Create a plot of the number of representatives in each caucus faceted by region. Include an informative title and axis labels.

- How does caucus membership compare across region? Write two observations from the graph to support your response.

7. *Are younger Democrats more likely to be in the Progressive Caucus than older Democrats?* To answer this question, create a new variable indicating whether the Democrat was born in the 1980’s (there has yet not been a Democrat elected to Congress who was born in the 1990s). Then, find the percentage of Democrats in each group (pre-1980 and 1980 or later) who are in the Progressive Caucus. *Hint: As a step along the way, you will also want to create a variable indicating if they are a Progressive Caucus member using `if_else` or `case_when`.*

- State your response to the question based on your output.

# Submission

Knit to PDF to create a PDF document. Stage and commit all remaining changes, 
and push your work to GitHub. Make sure all files are updated on your GitHub 
repo.

Only upload your PDF document to Gradescope. Before you submit the 
uploaded document, mark where each answer is to the exercises. If any answer 
spans multiple pages, then mark all pages. Associate the "Overall" section with 
the first page.

## Rubric

- Ex 1: 8 pts.

- Ex 2: 6 pts.

- Ex 3: 4 pts.

- Ex 4: 8 pts.

- Ex 5: 6 pts.

- Ex 6: 6 pts.

- Ex 7: 6 pts.

- Workflow and formatting - 6 pts
 - This includes having three meaningful commits, updating name, using
 tidyverse style and naming all code chunks.