---
title: "STA199 Lab"
date: "January 25, 2022"
output:
  xaringan::moon_reader:
    css: ["xaringan-themer.css", "slides.css"]
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightLines: true
      highlightStyle: solarized-light
      countIncrementalSlides: false
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)
```

## if_else

$x$ is a boolean value. What does this mean?

<br>
--

What do you think the code below does?

```{r ifelse-1, eval = F}
if(x == TRUE) {
  print("This above all; to thine own self be true.")
} else {
  print("False face must hide what the false heart doth know.")
}
```
---

## Example

Using the recent NYC `flights` dataset from class:
```{r load-library, message = F, echo = F}
library(nycflights13)
library(tidyverse)
flights = flights %>% 
  dplyr::filter(!is.na(dep_delay))
```

Let's categorize flights based on where they departed from. If a flight originated from Laguardia airport (LGA), we'll keep it as "LGA", otherwise we'll label it "Not LGA". To help with this, we'll use an `if_else` statement.


```{r better-example}
flights %>%
  mutate(new_origin = ifelse(origin == "LGA", "LGA", "Not LGA")) %>%
  select(origin, new_origin) %>%
  head(5)
    
```
  
  
---

  

